### ISSUE TITLE
Lavalink list not updated

### ISSUE THREAD

**Issue by idMJA** [appujet/lavalink-list#101]
After several pull requests from others and myself, I felt that the nodes on the web were not updated. Please check further, thank you.

**Comment by LucasB25** [comment]
Who are you talking about?

**Comment by idMJA** [comment]
I said: the lavalink list is not updated on the web

**Comment by hatry4** [comment]
same issue the website is not getting any updated from the latest pull request

**Comment by appujet** [comment]
fixed
